#!/bin/sh

# get folder with k8s objects
FOLDER=$1

# copy all objects to data folder
cp -r $FOLDER /data

# replace all placeholders with env variables in place
for entry in /data/*
do
  file=$(echo $entry | cut -d"/" -f3)

  /envsubst.sh "$(cat $entry)" > $entry
done

# authenticate kubectl
echo $K8S_CA > /ca.pem
kubectl config set-cluster default-cluster --insecure-skip-tls-verify=true --server=$K8S_MASTER_HOST 
kubectl config set-credentials default-admin --username=$K8S_ADMIN --password $K8S_PASSWORD
kubectl config set-context default-context --user=default-admin --cluster=default-cluster
kubectl config use-context default-context

kubectl config view

# deploy objects to k8s 
kubectl apply -f /data
