#!/bin/sh

# get folder with k8s objects
FOLDER=$1

# copy all objects to data folder
cp -r $FOLDER /data

# replace all placeholders with env variables in place
#for entry in /data/*
#do
  #file=$(echo $entry | cut -d"/" -f3)

  #/envsubst.sh "$(cat $entry)" > $entry
#done
for file in /data/*
do
    TPL=$(cat $file)
    for row in $(env)
    do
        IFS="="
        read key val <<< "$row"
        TPL=$(echo -n $TPL | sed "s\$\\\$$key\$$val\$")
    done
    echo -n $TPL > "/done/$(basename $file)"
done

# authenticate kubectl
kubectl config set-cluster default-cluster --insecure-skip-tls-verify=true --server=$K8S_MASTER_HOST 
kubectl config set-credentials default-admin --username=$K8S_ADMIN --password $K8S_PASSWORD
kubectl config set-context default-context --user=default-admin --cluster=default-cluster
kubectl config use-context default-context

# deploy objects to k8s 
cat /done/pod.yml
cat /done/ingress.yml
cat /done/service.yml

kubectl apply -f /done
