#!/bin/sh

# get folder with k8s objects
FOLDER=$1

# copy all objects to data folder
cp -r $FOLDER /data

# replace all placeholders with env variables in place
echo "\nReplacing placeholders with env variables..."
for entry in /data/*
do
  file=$(echo $entry | cut -d"/" -f3)

  /envsubst -i $entry -o $entry
done

# authenticate kubectl
echo "\nAuthenticating to cluster: $K8S_MASTER_HOST"
kubectl config set-cluster default-cluster --insecure-skip-tls-verify=true --server=$K8S_MASTER_HOST 
kubectl config set-credentials default-admin --username=$K8S_ADMIN --password $K8S_PASSWORD
kubectl config set-context default-context --user=default-admin --cluster=default-cluster
kubectl config use-context default-context

# deploy objects to k8s 
echo "\nDeploying objects..."
kubectl apply -f /data

